###############CPP STANDARD###############
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_BUILD_TYPE "Debug")
set(CMAKE_GENERATOR "Visual Studio 17 2022" CACHE INTERNAL "Visual Studio 17 2022" FORCE)

###############COMPILER FLAGS###############
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /NOLOGO /MD /DEBUG")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} /nologo /Z")
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG} /nologo /Z")

###############OUTPUT DIRS###############
set(BASE_OUTPUT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Build/${CMAKE_BUILD_TYPE})
set(OUT_BIN_DIR ${BASE_OUTPUT_DIR}/bin)
set(OUT_LIB_DIR ${BASE_OUTPUT_DIR}/lib)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${OUT_LIB_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${OUT_LIB_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY  ${OUT_BIN_DIR})

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${OUT_LIB_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${OUT_LIB_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG  ${OUT_BIN_DIR})

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${OUT_LIB_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${OUT_LIB_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE  ${OUT_BIN_DIR})

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO ${OUT_LIB_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO ${OUT_LIB_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO  ${OUT_BIN_DIR})

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL ${OUT_LIB_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL ${OUT_LIB_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL  ${OUT_BIN_DIR})

###############INCLUDES###############

