#this function copies .lib files from iconv to the build directory
function(copy_iconv_libs)
    find_package(IconV REQUIRED)
    if(IconV_FOUND)
        if(WIN32)
            file(GLOB ICONV_LIBS "${IconV_LIBRARIES}/*.lib")
            foreach(ICONV_LIB ${ICONV_LIBS})
                file(COPY ${ICONV_LIB} DESTINATION ${CMAKE_BINARY_DIR})
            endforeach()
        endif()
    else ()
        message(FATAL_ERROR "IconV not found")
    endif()
endfunction()
